export const INDUSTRIES = [
  'Accounting & Tax Services',
  'Advertising & Marketing',
  'Aerospace & Defense',
  'Agriculture & Farming',
  'Architecture & Design',
  'Automotive Repair & Service',
  'Banking & Financial Services',
  'Beauty & Cosmetics',
  'Biotechnology',
  'Business Consulting',
  'Catering & Food Service',
  'Childcare & Daycare',
  'Cleaning Services',
  'Construction & Contracting',
  'Dental Services',
  'Education & Tutoring',
  'Electronics & Technology',
  'Energy & Utilities',
  'Engineering Services',
  'Entertainment & Events',
  'Fashion & Apparel',
  'Fitness & Gyms',
  'Food & Beverage',
  'Funeral Services',
  'Furniture & Home Decor',
  'Graphic Design',
  'Grocery & Supermarkets',
  'Healthcare & Medical',
  'Home Improvement',
  'Hospitality & Hotels',
  'Human Resources',
  'Insurance',
  'Interior Design',
  'IT Services & Support',
  'Jewelry & Accessories',
  'Landscaping & Lawn Care',
  'Laundry & Dry Cleaning',
  'Law & Legal Services',
  'Logistics & Shipping',
  'Manufacturing',
  'Medical Devices',
  'Mortgage & Lending',
  'Moving & Relocation',
  'Non-Profit & Charity',
  'Optometry & Eyewear',
  'Painting & Decorating',
  'Pet Services & Veterinary',
  'Pharmaceuticals',
  'Photography & Videography',
  'Plumbing Services',
  'Printing & Publishing',
  'Real Estate',
  'Recruitment & Staffing',
  'Restaurants & Cafes',
  'Retail & E-Commerce',
  'Salons & Spas',
  'Security Services',
  'Software Development',
  'Telecommunications',
  'Transportation & Taxi',
  'Travel & Tourism',
  'Web Development',
  'Wholesale & Distribution',
] as const;

export type Industry = (typeof INDUSTRIES)[number];
